require:
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
  DisplayStyleGuide: true

# *********************** Bundler **************************
# https://docs.rubocop.org/rubocop/cops_bundler.html

Bundler/OrderedGems:
  Description: >-
    Gems within groups in the Gemfile should be alphabetically sorted.
  Enabled: true
  ConsiderPunctuation: true

# *********************** Layouts **************************
# https://docs.rubocop.org/rubocop/cops_layout.html

Layout/ClassStructure:
  Description: "Enforces a configured order of definitions within a class body."
  StyleGuide: "#consistent-classes"
  Enabled: true

Layout/LineLength:
  Description: "Checks that line length does not exceed the configured limit."
  AutoCorrect: true # this is false by default
  Exclude:
    - Gemfile

# *********************** Styles ***************************
# https://docs.rubocop.org/rubocop/cops_style.html

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition to frozen string literals by default.
  Enabled: true
  EnforcedStyle: never

Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  StyleGuide: "#consistent-string-literals"
  Enabled: true
  ConsistentQuotesInMultiline: true

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Description: >-
    Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
    { :a => 1, :b => 2 }.
  StyleGuide: "#hash-literals"
  Enabled: true
  EnforcedStyle: no_mixed_keys

Style/RedundantInterpolation:
  Description: >-
    This cop checks for strings that are just an interpolated expression.
  Enabled: false
