default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_DEV'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TEST'] %>
# production:
#   <<: *default
#   database: discussion_production
#   username: discussion
#   password: <%= ENV['DISCUSSION_DATABASE_PASSWORD'] %>
